# data process
preprocess:
  image_ids: /data2/share/data/coco/annotations/rand_ids.npy
  caption_annotation: 
    train: /data2/share/data/coco/annotations/captions_train2017.json
    val: /data2/share/data/coco/annotations/captions_val2017.json
  instance_annotation: 
    train: /data2/share/data/coco/annotations/instances_train2017.json
    val: /data2/share/data/coco/annotations/instances_val2017.json
  output_dir: /data2/share/data/coco/annotations/small_dataset

analysis:
  instance_annotation: 
    # train: /data2/share/data/coco/annotations/small_dataset/instances_train.json
    # val: /data2/share/data/coco/annotations/small_dataset/instances_val.json
    train: /data2/share/data/coco/annotations/instances_train2017.json
    val: /data2/share/data/coco/annotations/instances_val2017.json
  # output_dir: /data2/share/data/coco/annotations/small_dataset
  output_dir: /data2/share/data/coco/annotations
  
# data augmentation

tmp_path: tmp/f30k/

experimental:
  inst_desc_match:
    word2vec: /data2/private/cc/wheels/GoogleNews-vectors-negative300.bin
    image_path: /data2/share/data/coco/images/train2017
    caption_annotation: /data2/share/data/coco/annotations/small_dataset/captions_train.json
    instance_annotation: /data2/share/data/coco/annotations/small_dataset/instances_train.json
    output_dir: tmp/test/idm

segmentation:
  root: /data/share/UNITER/origin_imgs/flickr30k
  output_dir: tmp/Segmentations

extract_tree:
  stanza_dir: /data2/private/cc/experiment/ViLT/CIP/checkpoints/stanza
  # caption_annotation: /data2/share/data/coco/annotations/small_dataset/captions_train.json
  # instance_annotation: /data2/share/data/coco/annotations/small_dataset/instances_train.json
  caption_annotation: /data2/share/data/coco/annotations/captions_train2017.json
  instance_annotation: /data2/share/data/coco/annotations/instances_train2017.json
  output_dir: tmp

extract_tree_refcoco:
  stanza_dir: /data2/private/cc/experiment/ViLT/CIP/checkpoints/stanza
  dataroot: /data2/share/data/refcoco
  dataset: refcoco
  splitby: unc
  output_dir: tmp

inst_desc_match:
  word2vec: /data2/private/cc/wheels/GoogleNews-vectors-negative300.bin
  tree_path: ${extract_tree.output_dir}/id2tree.json
  image_path: /data2/share/data/coco/images/train2017
  # caption_annotation: /data2/share/data/coco/annotations/small_dataset/captions_train.json
  # instance_annotation: /data2/share/data/coco/annotations/small_dataset/instances_train.json
  caption_annotation: /data2/share/data/coco/annotations/captions_train2017.json
  instance_annotation: /data2/share/data/coco/annotations/instances_train2017.json
  output_dir: ${tmp_path}/idm_results
  th_wordsim: 0.5
  th_coverage: 
    - 0.1
    - 0.7
  visualize: True

inst_desc_match_f30k:
  root: /data2/share/data/flickr30k-entities
  image_path: /data2/share/data/flickr30k-entities/flickr30k-images
  output_dir: ${tmp_path}/idm_results
  visualize: True

inst_desc_match_refcoco:
  dataroot: /data2/share/data/refcoco
  dataset: refcoco
  splitby: unc
  output_dir: ${tmp_path}/idm_results

phrase_grounding:
  image_path: /data2/share/data/coco/images/train2017
  caption_annotation: /data2/share/data/coco/annotations/small_dataset/captions_train.json
  instance_annotation: /data2/share/data/coco/annotations/small_dataset/instances_train.json
  output_dir: ${tmp_path}/pg_results
  th_bbox_overlap: 0.8

crop_inpaint:
  template_annotation: ${inst_desc_match.output_dir}/templates.json
  template_path: ${tmp_path}/origin_images
  inpaint:
    code_path: /data2/private/cc/experiment/lama
    model_path: /data2/private/cc/experiment/lama/big-lama
    indir: ${crop_inpaint.template_path}
    outdir: ${tmp_path}/inpaint_images
    device: 
      - cuda:4
      - cuda:5
      - cuda:6
      - cuda:7

augment:
  k: 1
  num_sample: 5000
  seed: 18
  idm_dir: ${inst_desc_match.output_dir}
  inpaint_dir: ${crop_inpaint.inpaint.outdir}
  # inpaint_dir: ${crop_inpaint.template_path}
  output_dir: ${tmp_path}/augment_results
  th_matchscore: 0.7
  num_processes: 1

evaluate:
  data_dir: ${augment.output_dir}
  # data_dir: /data2/share/data/flickr30k-entities/flickr30k-images
  output_path: ${augment.output_dir}/scores.txt
  device: 'cuda:4'
  batch_size: 100
