word2vec: /data2/private/cc/wheels/GoogleNews-vectors-negative300.bin
image_path: /data2/share/data/coco/images/val2017
caption_annotation: /data2/share/data/coco/annotations/captions_val2017.json
instance_annotation: /data2/share/data/coco/annotations/instances_val2017.json
categories: 
  - dog
th_wordsim: 0.5